Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 128
      Handler: controller.App
      CodeUri: C:\Development\Codebase\TodoistWebhook\Lambdas\ApiGatewayForWebhook\ApiGatewayForWebhookLambda
      Runtime: java17
      Architectures:
        - x86_64