Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 128
      Handler: controller.App::handleRequest
      CodeUri: C:\Users\Vikram\Downloads\Lambdas\LambdasTodoist\ApiGatewayForWebhook\ApiGatewayForWebhookLambda
      Runtime: java17
      Architectures:
        - x86_64